### ISSUE TITLE
Multiple proxy elements

### ISSUE THREAD

**Issue by rssems** [mamezito/moveWithArc-FramerJS-module#2]
<img width="245" alt="screen shot 2017-06-23 at 10 23 14 pm" src="https://user-images.githubusercontent.com/847648/27505967-9db53f7e-5862-11e7-9da3-5684106975aa.png">

It would be nice to destroy proxy element once its job is done.

**Comment by mamezito-zz** [comment]
make sense, will update that

**Comment by mamezito-zz** [comment]
I rewrote module a little bit, according to some hint from @gk3 a long ago:)
also added timing attribute https://framer.cloud/AThCD
